"""Revoke sessions on account changes, preserve assessments and durable records."""
from alembic import op
import sqlalchemy as sa

revision = "20260911_0005"
down_revision = "20260911_0004"
branch_labels = None
depends_on = None


def upgrade():
    op.add_column("venture_members", sa.Column("appointed_by", sa.String(64), nullable=True))
    op.add_column("venture_skill_assessments", sa.Column("supersedes_id", sa.String(80), nullable=True))
    op.add_column("venture_skill_assessments", sa.Column("revoked", sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column("users", sa.Column("session_version", sa.Integer(), nullable=False, server_default="0"))
    op.drop_index("ux_venture_skill_user", table_name="venture_skill_assessments")
    op.create_index("ix_venture_skill_user", "venture_skill_assessments", ["venture_id", "skill_id", "user_id"])
    op.create_table("application_records",
        sa.Column("namespace", sa.String(64), primary_key=True),
        sa.Column("id", sa.String(128), primary_key=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    # Old AI evidence was generated by a keyword heuristic, not a validated evaluator.
    op.execute("UPDATE evidence SET status = 'unverified', strength = 'standard' WHERE review_type = 'ai'")
    op.execute("UPDATE users SET session_version = 1")
    # Preserve previous confirmations, but require independent reappointment and risk review.
    bind = op.get_bind()
    metadata = sa.MetaData()
    ventures = sa.Table("ventures", metadata, autoload_with=bind)
    for row in bind.execute(sa.select(ventures.c.id, ventures.c.governance)).mappings():
        governance = dict(row["governance"] or {})
        governance.update(riskConfirmed=False, riskState="再判定待ち", riskRecheckReason="独立確認者の任命と権限を再確認してください")
        bind.execute(ventures.update().where(ventures.c.id == row["id"]).values(governance=governance))
    op.execute("UPDATE notification_delivery_settings SET email_enabled = false, push_enabled = false")
    # Existing external deliveries cannot be retrospectively certified as sent.
    jobs = sa.Table("notification_delivery_jobs", metadata, autoload_with=bind)
    inbox = sa.Table("notifications", metadata, autoload_with=bind)
    for job in bind.execute(sa.select(jobs)).mappings():
        channels = set(job["channels"] or [])
        if channels - {"in_app"}:
            bind.execute(jobs.update().where(jobs.c.id == job["id"]).values(status="failed",
                last_error="External delivery was not implemented; receipt is unverified"))
        elif job["status"] in {"queued", "retrying", "processing"}:
            if "in_app" in channels and not bind.execute(sa.select(inbox.c.id).where(inbox.c.id == job["id"])).first():
                bind.execute(inbox.insert().values(id=job["id"], **{key: job[key] for key in
                    ("tenant_id", "user_id", "category", "title", "body", "target_url", "is_important")}))
            bind.execute(jobs.update().where(jobs.c.id == job["id"]).values(status="completed", result_json={"deliveredChannels": list(channels)}))


def downgrade():
    raise RuntimeError("Assessment history cannot be safely collapsed. Restore a reviewed backup instead.")
