from __future__ import annotations

from typing import Protocol

from domain.models import (
    AuditLogEvent,
    Company,
    ConsentRecord,
    CurriculumVersion,
    Goal,
    Message,
    MessageTemplateAuditLog,
    MessageTemplate,
    MessageThread,
    NotificationDeliverySetting,
    Notification,
    ModerationCase,
    Opportunity,
    OpportunityApplicationSnapshot,
    PortfolioArtifact,
    PublicProfileSetting,
    ProgressEvent,
    Roadmap,
    UserAccount,
)


class ConsentRepository(Protocol):
    def save(self, consent: ConsentRecord) -> ConsentRecord: ...
    def list_by_user(self, user_id: str) -> list[ConsentRecord]: ...


class GoalRepository(Protocol):
    def save(self, goal: Goal) -> Goal: ...
    def get(self, goal_id: str) -> Goal | None: ...
    def list_by_user(self, user_id: str) -> list[Goal]: ...


class RoadmapRepository(Protocol):
    def save(self, roadmap: Roadmap) -> Roadmap: ...
    def get(self, roadmap_id: str) -> Roadmap | None: ...
    def list_by_user(self, user_id: str) -> list[Roadmap]: ...
    def list_all(self) -> list[Roadmap]: ...


class CurriculumRepository(Protocol):
    def list_published(self) -> list[CurriculumVersion]: ...
    def get(self, curriculum_version_id: str) -> CurriculumVersion | None: ...
    def save(self, curriculum_version: CurriculumVersion) -> CurriculumVersion: ...


class ProgressRepository(Protocol):
    def save(self, event: ProgressEvent) -> ProgressEvent | None: ...
    def list_by_user(self, user_id: str) -> list[ProgressEvent]: ...


class OpportunityApplicationRepository(Protocol):
    def set_state(self, user_id: str, opportunity_id: str, state: str) -> str: ...
    def get_state(self, user_id: str, opportunity_id: str) -> str: ...
    def list_by_user(self, user_id: str) -> dict[str, str]: ...
    def list_records_by_user(self, user_id: str) -> list[OpportunityApplicationSnapshot]: ...


class OpportunityRepository(Protocol):
    def list_all(self) -> list[Opportunity]: ...
    def get(self, opportunity_id: str) -> Opportunity | None: ...


class CompanyRepository(Protocol):
    def list_all(self) -> list[Company]: ...
    def get(self, company_id: str) -> Company | None: ...
    def save(self, value: Company) -> Company: ...
    def get_many(self, company_ids: list[str]) -> list[Company]: ...


class ModerationRepository(Protocol):
    def list_all(self) -> list[ModerationCase]: ...
    def get(self, case_id: str) -> ModerationCase | None: ...
    def save(self, value: ModerationCase) -> ModerationCase: ...
    def get_many(self, case_ids: list[str]) -> list[ModerationCase]: ...


class PortfolioArtifactRepository(Protocol):
    def list_by_user(self, user_id: str) -> list[PortfolioArtifact]: ...
    def get_by_user(self, user_id: str, artifact_id: str) -> PortfolioArtifact | None: ...


class NotificationRepository(Protocol):
    def list_by_user(self, user_id: str) -> list[Notification]: ...
    def mark_read(self, user_id: str, notification_id: str) -> Notification | None: ...
    def mark_all_read(self, user_id: str) -> int: ...


class NotificationDeliverySettingRepository(Protocol):
    def list_by_user(self, user_id: str) -> list[NotificationDeliverySetting]: ...
    def upsert_by_user(
        self,
        user_id: str,
        category: str,
        email_enabled: bool,
        in_app_enabled: bool,
        push_enabled: bool,
    ) -> NotificationDeliverySetting: ...


class MessageRepository(Protocol):
    def list_threads_by_user(self, user_id: str) -> list[MessageThread]: ...
    def get_thread_by_user(self, user_id: str, thread_id: str) -> MessageThread | None: ...
    def list_messages(self, thread_id: str) -> list[Message]: ...
    def append_message(self, message: Message) -> Message: ...


class MessageTemplateRepository(Protocol):
    def list_templates(self) -> list[MessageTemplate]: ...
    def get_template(self, template_id: str) -> MessageTemplate | None: ...
    def save_template(self, template: MessageTemplate) -> MessageTemplate: ...
    def update_template(self, template: MessageTemplate) -> MessageTemplate | None: ...
    def delete_template(self, template_id: str) -> bool: ...


class MessageTemplateAuditLogRepository(Protocol):
    def append_log(self, value: MessageTemplateAuditLog) -> MessageTemplateAuditLog: ...
    def list_logs(self, limit: int = 100) -> list[MessageTemplateAuditLog]: ...


class PublicProfileSettingRepository(Protocol):
    def get_by_user(self, user_id: str) -> PublicProfileSetting | None: ...
    def upsert(self, value: PublicProfileSetting) -> PublicProfileSetting: ...


class UserRepository(Protocol):
    def get(self, user_id: str) -> UserAccount | None: ...
    def save(self, user: UserAccount) -> UserAccount: ...
    def list_users(self) -> list[UserAccount]: ...


class AuditLogRepository(Protocol):
    def append(self, value: AuditLogEvent) -> AuditLogEvent: ...
    def list_logs(
        self,
        limit: int = 100,
        event_type: str | None = None,
        actor_user_id: str | None = None,
        occurred_from: str | None = None,
        occurred_to: str | None = None,
    ) -> list[AuditLogEvent]: ...
