from __future__ import annotations

from typing import Protocol

from domain.models import (
    AuditLogEvent,
    Company,
    ConsentRecord,
    CurriculumVersion,
    Goal,
    NotificationDeliverySetting,
    Notification,
    ModerationCase,
    ProgressEvent,
    Roadmap,
    UserAccount,
)


class ConsentRepository(Protocol):
    def save(self, consent: ConsentRecord) -> ConsentRecord: ...
    def list_by_user(self, user_id: str) -> list[ConsentRecord]: ...


class GoalRepository(Protocol):
    def save(self, goal: Goal) -> Goal: ...
    def get(self, goal_id: str) -> Goal | None: ...
    def list_by_user(self, user_id: str) -> list[Goal]: ...


class RoadmapRepository(Protocol):
    def save(self, roadmap: Roadmap) -> Roadmap: ...
    def get(self, roadmap_id: str) -> Roadmap | None: ...
    def list_by_user(self, user_id: str) -> list[Roadmap]: ...
    def list_all(self) -> list[Roadmap]: ...


class CurriculumRepository(Protocol):
    def list_published(self) -> list[CurriculumVersion]: ...
    def get(self, curriculum_version_id: str) -> CurriculumVersion | None: ...
    def save(self, curriculum_version: CurriculumVersion) -> CurriculumVersion: ...


class ProgressRepository(Protocol):
    def save(self, event: ProgressEvent) -> ProgressEvent | None: ...
    def list_by_user(self, user_id: str) -> list[ProgressEvent]: ...


class CompanyRepository(Protocol):
    def list_all(self) -> list[Company]: ...
    def get(self, company_id: str) -> Company | None: ...
    def save(self, value: Company) -> Company: ...
    def get_many(self, company_ids: list[str]) -> list[Company]: ...


class ModerationRepository(Protocol):
    def list_all(self) -> list[ModerationCase]: ...
    def get(self, case_id: str) -> ModerationCase | None: ...
    def save(self, value: ModerationCase) -> ModerationCase: ...
    def get_many(self, case_ids: list[str]) -> list[ModerationCase]: ...


class NotificationRepository(Protocol):
    def list_by_user(self, user_id: str) -> list[Notification]: ...
    def mark_read(self, user_id: str, notification_id: str) -> Notification | None: ...
    def mark_all_read(self, user_id: str) -> int: ...


class NotificationDeliverySettingRepository(Protocol):
    def list_by_user(self, user_id: str) -> list[NotificationDeliverySetting]: ...
    def upsert_by_user(
        self,
        user_id: str,
        category: str,
        email_enabled: bool,
        in_app_enabled: bool,
        push_enabled: bool,
    ) -> NotificationDeliverySetting: ...


class UserRepository(Protocol):
    def get(self, user_id: str) -> UserAccount | None: ...
    def save(self, user: UserAccount) -> UserAccount: ...
    def list_users(self) -> list[UserAccount]: ...


class AuditLogRepository(Protocol):
    def append(self, value: AuditLogEvent) -> AuditLogEvent: ...
    def list_logs(
        self,
        limit: int = 100,
        event_type: str | None = None,
        actor_user_id: str | None = None,
        occurred_from: str | None = None,
        occurred_to: str | None = None,
    ) -> list[AuditLogEvent]: ...
